apiVersion: apps/v1
kind: Deployment
metadata:
  name: jobber-kibana
  namespace: production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jobber-kibana
  template:
    metadata:
      labels:
        app: jobber-kibana
    spec:
      containers:
        - name: jobber-kibana
          image: docker.elastic.co/kibana/kibana:8.15.0
          resources:
            limits:
              cpu: "1500m"
              memory: "1Gi"
            requests:
              cpu: 250m
              memory: 1Gi
          ports:
            - name: jobber-kibana
              containerPort: 5601
          env:
            - name: ELASTICSEARCH_HOSTS
              # http://<service-name>.<namespace>.svc.cluster.local:<port-number>
              value: http://jobber-elastic.production.svc.cluster.local:9200
            - name: ELASTICSEARCH_USERNAME
              value: kibana_system
            - name: ELASTICSEARCH_PASSWORD
              # add to secret file
              value: kibana
            - name: ELASTICSEARCH_SERVICEACCOUNT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: jobber-backend-secret
                  # if elasticsearch restarted, we need to create the service account
                  key: jobber-elasticsearch-service-account-token
          volumeMounts:
            - name: kibana-config
              mountPath: /usr/share/kibana/config
      volumes:
        - name: kibana-config
          configMap:
            name: kibana-config
